baseURL = "https://navymerianda.com/"
languageCode = "en-us"
title = "Navy Merianda"
theme = ""
disqusShortname = "navymerianda" # delete this to disable disqus comments
googleAnalytics = "UA-122105448-1"
enableRobotsTXT = true
canonifyURLs = true


[[redirects]]
  from = "/*"
  to = "https://navymerianda.com/post/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[params]
    author = "Navy Merianda"
    description = "Developer. Photographer. Tech Enthusiast."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "PT Serif" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "images/ppLogo.png"
    favicon = "images/icn.png"

[taxonomies]
  tag = "tags"
  category = "categories"

#[[menu.main]]
    #url = "/"
    #name = "HOME"
    #weight = 1

[[menu.main]]
    url = "/post/"
    name = "BLOG"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "PROJECTS"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "TAGS"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:navymerianda@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/navymerianda/"
    name = "github"
    weight = 2

#[[menu.icon]]
    #url = "https://navymerianda.com/"
    #name = "home"
    #weight = 3

#[[menu.icon]]
    #url = "https://www.linkedin.com/in/username/"
    #name = "linkedin"
    #weight = 4

#[[menu.icon]]
    #url = "https://www.stackoverflow.com/username/"
    #name = "stack-overflow"
    #weight = 5

